spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          fetch_size: 2000
  datasource:
    url: jdbc:mysql://localhost:3306/employees
    username: admin
    password: admin123

#SQL statement logging configuration
decorator:
  datasource:
    enabled: true
    datasource-proxy:
      logging: slf4j
      count-query: false
      json-format: false
      multiline: true
      query:
        enable-logging: true
        log-level: info
        logger-name: "net.ttddyy.dsproxy.listener.logging.SLF4JQueryLoggingListener"
      slow-query:
        enable-logging: true
        log-level: info
        logger-name: "net.ttddyy.dsproxy.listener.logging.SLF4JSlowQueryListener"
        threshold: 300

logging:
  level:
    root: info