spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/employees
    username: admin
    password: admin123

decorator:
  datasource:
    #SQL statement logging configuration
    datasource-proxy:
      logging: slf4j
      count-query: false
      json-format: false
      multiline: true
      query:
        enable-logging: true
        log-level: info
        logger-name: "net.ttddyy.dsproxy.listener.logging.SLF4JQueryLoggingListener"
      slow-query:
        enable-logging: true
        log-level: info
        logger-name: "net.ttddyy.dsproxy.listener.logging.SLF4JSlowQueryListener"
        threshold: 300
    # reactive connection pooling
    flexy-pool:
     acquiring-strategy:
       increment-pool:
         max-overflow-pool-size: 10
         timeout-millis: 500
       retry:
         attempts: 2
     metrics:
       reporter:
         jmx:
           enabled: false

logging:
  level:
    root: info